Repository ReDI-School/intro-java, pull requests merged in 2022-03, with the labels that each got.

#51 fix(course-material): Make course material changes for clarity
  lesson5/index.md
Labels: enhancement, ready for review

#52 fix(course-exercises): Make course exercise changes for clarity
  lesson5/if_loops.md
Labels: ready for review, trivial

#54 (course-solutions): Clean up solutions in line with exercises
  lesson5/if_loops.md
  lesson5/if_loops_solutions.md
Labels: ready for review

#55 Updates to chapter 4 - decision statements
  lesson4/decision.md
  lesson4/index.md
Labels: ready for review
